// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-FKzQM_eq01jGz9cqXRMBIMeWOIuvkvI',
    appId: '1:83929607850:web:5334f9d3ac5608b5b92ad3',
    messagingSenderId: '83929607850',
    projectId: 'flutterapp-71cf3',
    authDomain: 'flutterapp-71cf3.firebaseapp.com',
    storageBucket: 'flutterapp-71cf3.appspot.com',
    measurementId: 'G-W54388F5TK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhc489A81JC6He5O0CegfotyAEmx1bKBI',
    appId: '1:83929607850:android:4e84d6d42b34e06fb92ad3',
    messagingSenderId: '83929607850',
    projectId: 'flutterapp-71cf3',
    storageBucket: 'flutterapp-71cf3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxF18Yod-Shb_Fs2jM2atirPrOwRD7L8Y',
    appId: '1:83929607850:ios:fb80b2044854b3e1b92ad3',
    messagingSenderId: '83929607850',
    projectId: 'flutterapp-71cf3',
    storageBucket: 'flutterapp-71cf3.appspot.com',
    iosBundleId: 'com.example.first',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxF18Yod-Shb_Fs2jM2atirPrOwRD7L8Y',
    appId: '1:83929607850:ios:6c89fb6c1ed46557b92ad3',
    messagingSenderId: '83929607850',
    projectId: 'flutterapp-71cf3',
    storageBucket: 'flutterapp-71cf3.appspot.com',
    iosBundleId: 'com.example.first.RunnerTests',
  );
}
